# Each new term in the F ibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def Fibonacci():
    a, b = 1, 2
    while True:
        yield a
        a, b = b, a+b
sum = 0
for i in Fibonacci():
    if i > 4000000:
        break
    if i % 2 == 0:
        sum += i
print sum
